name: CI/CD - Build & Push Docker Images

on:
  push:
    branches:
      - myself_deploy      
    tags:
      - 'v*'   

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            danlylacov/devops_vs_ai:backend-latest
            danlylacov/devops_vs_ai:backend-${{ github.sha }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            danlylacov/devops_vs_ai:frontend-latest
            danlylacov/devops_vs_ai:frontend-${{ github.sha }}
