name: CI/CD Pipeline

on:
  push:
    branches:
      - myself_deploy

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t danlylacov/devops_vs_ai:backend-latest ./backend
          docker push danlylacov/devops_vs_ai:backend-latest

      - name: Build and push frontend
        run: |
          docker build -t danlylacov/devops_vs_ai:frontend-latest ./frontend
          docker push danlylacov/devops_vs_ai:frontend-latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app
            docker compose pull
            docker compose up -d
            docker system prune -f
